      - name: Publish Worker with Wrangler
        uses: cloudflare/wrangler-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # If you have multiple Workers, set the script name; 
          # otherwise it uses the name in wrangler.toml
          # e.g. script: my-worker-script
